export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const ADD_TO_API = 'ADD_TO_API';
export const REMOVE_FROM_API = 'REMOVE_FROM_API';

export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST';
export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS';
export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL';
