export const GET_CART_ITEMS_REQUEST = 'GET_CART_ITEMS_REQUEST';
export const GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS';
export const GET_CART_ITEMS_FAIL = 'GET_CART_ITEMS_FAIL';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const CLEAR_CART = 'CLEAR_CART';
